package java_code.Warehouse;

/**
* java_code/Warehouse/APIMessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 22:25:38 ICT Th? hai, ngày 18 tháng ba nãm 2013
*/

public final class APIMessageHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.Warehouse.APIMessage value = null;

  public APIMessageHolder ()
  {
  }

  public APIMessageHolder (java_code.Warehouse.APIMessage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.APIMessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.APIMessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.APIMessageHelper.type ();
  }

}
