package java_code.Warehouse;


/**
* java_code/Warehouse/APIMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, March 13, 2013 10:37:51 AM GMT+07:00
*/

public final class APIMessage implements org.omg.CORBA.portable.IDLEntity
{
  public short code = (short)0;
  public String description = null;

  public APIMessage ()
  {
  } // ctor

  public APIMessage (short _code, String _description)
  {
    code = _code;
    description = _description;
  } // ctor

} // class APIMessage
