package java_code.Warehouse;


/**
* java_code/Warehouse/Item.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 23:35:39 ICT Th? b?y, ngày 09 tháng ba nãm 2013
*/

public final class Item implements org.omg.CORBA.portable.IDLEntity
{
  public short itemCode = (short)0;
  public String description = null;
  public short qty = (short)0;
  public short date = (short)0;
  public short cost = (short)0;

  public Item ()
  {
  } // ctor

  public Item (short _itemCode, String _description, short _qty, short _date, short _cost)
  {
    itemCode = _itemCode;
    description = _description;
    qty = _qty;
    date = _date;
    cost = _cost;
  } // ctor

} // class Item
