package java_code.Warehouse;


/**
* java_code/Warehouse/ItemTypeListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 22:19:01 ICT Th? b?y, ngày 09 tháng ba nãm 2013
*/

public final class ItemTypeListHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.Warehouse.ItemType value[] = null;

  public ItemTypeListHolder ()
  {
  }

  public ItemTypeListHolder (java_code.Warehouse.ItemType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.ItemTypeListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.ItemTypeListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.ItemTypeListHelper.type ();
  }

}
