package java_code.Warehouse;


/**
* java_code/Warehouse/ItemListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 17:18:41 ICT Ch? nh?t, ngày 07 tháng tý nãm 2013
*/

public final class ItemListHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.Warehouse.Item value[] = null;

  public ItemListHolder ()
  {
  }

  public ItemListHolder (java_code.Warehouse.Item[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.ItemListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.ItemListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.ItemListHelper.type ();
  }

}
