package java_code.Warehouse;


/**
* java_code/Warehouse/Role.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, March 13, 2013 10:37:51 AM GMT+07:00
*/

public final class Role implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public String role_name = null;

  public Role ()
  {
  } // ctor

  public Role (short _id, String _role_name)
  {
    id = _id;
    role_name = _role_name;
  } // ctor

} // class Role
