package java_code.Warehouse;


/**
* java_code/Warehouse/UserListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 23:33:44 ICT Th? hai, ngày 01 tháng tý nãm 2013
*/

public final class UserListHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.Warehouse.User value[] = null;

  public UserListHolder ()
  {
  }

  public UserListHolder (java_code.Warehouse.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.UserListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.UserListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.UserListHelper.type ();
  }

}
