package java_code.Warehouse;


/**
* java_code/Warehouse/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 22:19:01 ICT Th? b?y, ngày 09 tháng ba nãm 2013
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public String password = null;
  public short role_id = (short)0;
  public String role_name = null;

  public User ()
  {
  } // ctor

  public User (short _id, String _password, short _role_id, String _role_name)
  {
    id = _id;
    password = _password;
    role_id = _role_id;
    role_name = _role_name;
  } // ctor

} // class User
