package java_code.Warehouse;


/**
* java_code/Warehouse/WarehouseIdListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, April 5, 2013 3:56:39 PM GMT+07:00
*/

public final class WarehouseIdListHolder implements org.omg.CORBA.portable.Streamable
{
  public short value[] = null;

  public WarehouseIdListHolder ()
  {
  }

  public WarehouseIdListHolder (short[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.WarehouseIdListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.WarehouseIdListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.WarehouseIdListHelper.type ();
  }

}
