package java_code.Warehouse;


/**
* java_code/Warehouse/WHM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 23:08:36 ICT Th? ba, ngày 12 tháng ba nãm 2013
*/

public interface WHM extends WHMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WHM
