package java_code.Warehouse;


/**
* java_code/Warehouse/WHMHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 22:25:39 ICT Th? hai, ngày 18 tháng ba nãm 2013
*/

abstract public class WHMHelper
{
  private static String  _id = "IDL:Warehouse/WHM:1.0";

  public static void insert (org.omg.CORBA.Any a, java_code.Warehouse.WHM that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static java_code.Warehouse.WHM extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (java_code.Warehouse.WHMHelper.id (), "WHM");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static java_code.Warehouse.WHM read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WHMStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, java_code.Warehouse.WHM value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static java_code.Warehouse.WHM narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof java_code.Warehouse.WHM)
      return (java_code.Warehouse.WHM)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      java_code.Warehouse._WHMStub stub = new java_code.Warehouse._WHMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static java_code.Warehouse.WHM unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof java_code.Warehouse.WHM)
      return (java_code.Warehouse.WHM)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      java_code.Warehouse._WHMStub stub = new java_code.Warehouse._WHMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
