package java_code.Warehouse;

/**
* java_code/Warehouse/WHMHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, April 5, 2013 3:56:39 PM GMT+07:00
*/

public final class WHMHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.Warehouse.WHM value = null;

  public WHMHolder ()
  {
  }

  public WHMHolder (java_code.Warehouse.WHM initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.Warehouse.WHMHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.Warehouse.WHMHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.Warehouse.WHMHelper.type ();
  }

}
