package java_code.Warehouse;


/**
* java_code/Warehouse/WHMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 23:08:36 ICT Th? ba, ngày 12 tháng ba nãm 2013
*/

public interface WHMOperations 
{
  String login (String username, String password, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void logout (String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void addUser (String username, String password, short role_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void removeUser (short user_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  java_code.Warehouse.User getLoggedUser (String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void updateUser (java_code.Warehouse.User user, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  java_code.Warehouse.Role getRole (short role_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);

  //Lich su nhap kho
  java_code.Warehouse.Item[] getItemList (short warehouse_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);

  //Tim san pham tren 1 kho
  java_code.Warehouse.Item getItem (short warehouse_id, short itemCode, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);

  //Tim san pham tren tat ca kho
  java_code.Warehouse.Item getItemInAllWareHouses (short itemCode, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);

  //Nhap kho
  void addItem (short warehouse_id, short itemCode, short qty, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void removeItem (short warehouse_id, short itemCode, short qty, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);

  //Xuat kho
  java_code.Warehouse.ItemType[] getItemTypeList (short warehouse_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  java_code.Warehouse.ItemType getItemType (short warehouse_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  java_code.Warehouse.ItemType addItemType (short warehouse_id, java_code.Warehouse.ItemType item_type, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  void removeItemType (short warehouse_id, short item_type_id, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  java_code.Warehouse.ItemType updateItemType (short warehouse_id, java_code.Warehouse.ItemType item_type, String token, java_code.Warehouse.APIMessageListHolder apiMessageList);
  String sayHello ();
  void shutdown ();
} // interface WHMOperations
