package java_code.HelloApp;

/**
* java_code/HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 19:44:22 ICT Ch? nh?t, ngày 24 tháng hai nãm 2013
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public java_code.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (java_code.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = java_code.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    java_code.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return java_code.HelloApp.HelloHelper.type ();
  }

}
