package java_code.HelloApp;


/**
* java_code/HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 19:44:22 ICT Ch? nh?t, ngày 24 tháng hai nãm 2013
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
