package java_code.HelloApp;


/**
* java_code/HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 19:44:22 ICT Ch? nh?t, ngày 24 tháng hai nãm 2013
*/

public interface HelloOperations 
{
  String sayHello ();
  int calc (int a, int b);
  void shutdown ();
} // interface HelloOperations
